# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Home"
    name: "home"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.md"
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'home' }
          - { label: Title, name: title, widget: string }
          - { label: Landing Title, name: landing-title, widget: string, default: 'Hi, my name is Forty' }
          - { label: "Tile", name: "show_tile", widget: "boolean", default: false }
          - { label: Background, name: background, widget: image }
          - { label: "Content", name: "body", widget: "markdown" }